# Generated by Django 5.0.6 on 2024-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name')),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title')),
                ('description', models.TextField(db_column='Description')),
                ('poster', models.URLField(db_column='Poster')),
                ('trailer', models.URLField(db_column='Trailer')),
                ('date', models.DateField(db_column='Date')),
                ('country', models.CharField(db_column='Country')),
                ('duration', models.PositiveIntegerField(db_column='Duration')),
                ('slug', models.SlugField(default='', unique=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'db_table': 'Film',
            },
        ),
    ]
