# Generated by Django 5.0.6 on 2024-05-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age',
            field=models.FloatField(db_column='Age', default=10.0),
        ),
        migrations.AddField(
            model_name='film',
            name='eng_title',
            field=models.CharField(db_column='English title', default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.PositiveIntegerField(db_column='Rating', default=18),
        ),
        migrations.AddField(
            model_name='film',
            name='slogan',
            field=models.TextField(db_column='Slogan', default=''),
        ),
    ]
