# Generated by Django 5.0.6 on 2024-05-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_film_age_film_eng_title_film_rating_film_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.PositiveIntegerField(db_column='Age', default=18),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(db_column='Rating', default=10.0),
        ),
    ]
