# Generated by Django 5.0.6 on 2024-05-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_film_age_alter_film_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='age',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
    ]
