# Generated by Django 5.0.6 on 2024-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_film_age_remove_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age',
            field=models.PositiveIntegerField(db_column='Age', default=18),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(db_column='Rating', default=9.6),
        ),
    ]
