# Generated by Django 5.0.6 on 2024-05-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
