# Generated by Django 5.0.6 on 2024-05-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
