# Generated by Django 5.0.6 on 2024-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(db_column='Room name', default='<function uuid4 at 0x106068ea0>', editable=False),
        ),
    ]
