# Generated by Django 5.0.6 on 2024-05-21 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='film',
            field=models.ForeignKey(db_column='FilmID', null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.film'),
        ),
        migrations.AddField(
            model_name='room',
            name='pause',
            field=models.BooleanField(db_column='Pause', default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='timer',
            field=models.FloatField(db_column='Time video', default=0),
        ),
    ]
