# Generated by Django 5.0.6 on 2024-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_room_film_room_pause_room_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pause',
            field=models.BooleanField(db_column='Pause', default=True),
        ),
    ]
