# Generated by Django 5.0.6 on 2024-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.PositiveIntegerField(db_column='Age'),
        ),
        migrations.AlterField(
            model_name='film',
            name='eng_title',
            field=models.CharField(db_column='English title'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(db_column='Rating'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slogan',
            field=models.TextField(db_column='Slogan'),
        ),
    ]
