# Generated by Django 5.0.6 on 2024-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_roomusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_link',
            field=models.CharField(db_column='Film link', null=True),
        ),
    ]
