# Generated by Django 5.0.6 on 2024-05-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(db_column='RoleID', default=2, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
