# Generated by Django 5.0.6 on 2024-05-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('request_sent', 'Заявка отправлена'), ('friends', 'Друзья'), ('request_declined', 'Заявка отклонена')], db_column='Status', default='request_declined')),
                ('receiver', models.ForeignKey(db_column='ReceiverID', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='SenderID', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Friends',
            },
        ),
    ]
