# Generated by Django 5.0.6 on 2024-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('request_sent', 'Заявка отправлена'), ('friends', 'Друзья')], db_column='Status', default='request_declined'),
        ),
    ]
