# Generated by Django 5.0.6 on 2024-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='period',
            field=models.IntegerField(db_column='Subscription period', default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.BooleanField(db_column='Subscription', default=False),
        ),
    ]
