# Generated by Django 5.0.6 on 2024-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_period_customuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_date',
            field=models.DateField(db_column='Notification date', null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='room_link',
            field=models.CharField(db_column='Room link', null=True),
        ),
    ]
